
test:
	java -jar ~/bin/JsTestDriver.jar --tests all --captureConsole

run_browser:
	java -jar ~/bin/JsTestDriver.jar --port 11981 --browser google-chrome

run_server:
	java -jar ~/bin/JsTestDriver.jar --port 11981
